version: 1
# List of env variables used during compilation.
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

# Flags for the compiler.
flags:
  - -trimpath
  - -tags=netgo

goos: linux # same values as GOOS env variable.
goarch: 
  - amd64
  - arm64
  - armv7

# Entrypoint to compile. Default is the root directory.
# main: ./path/to/main.go

# Binary name.
# {{ .Os }} will be replaced by goos field in the config file.
# {{ .Arch }} will be replaced by goarch field in the config file.
binary: systemd-status-leds-{{ .Arch }}-{{ .Os }}

# (Optional) ldflags generated dynamically in the workflow, and set as the `env` input variables in the workflow.
ldflags:
  - ""
